// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmdc3cYzkdbLD_uEI-XnQbtFn_AZhkKY4',
    appId: '1:409763267925:web:3d39920e8bff5a225a1bdc',
    messagingSenderId: '409763267925',
    projectId: 'safdsaf-d85f6',
    authDomain: 'safdsaf-d85f6.firebaseapp.com',
    databaseURL: 'https://safdsaf-d85f6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safdsaf-d85f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAlHgLuMeYErjqagxsMkgi1_sdg3v_6E8',
    appId: '1:409763267925:android:622fe6a0367ef2355a1bdc',
    messagingSenderId: '409763267925',
    projectId: 'safdsaf-d85f6',
    databaseURL: 'https://safdsaf-d85f6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safdsaf-d85f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuiVpUbCZlL9ifgxE6SLin8-z7-hqGNpQ',
    appId: '1:409763267925:ios:fb1a9ac83529af6e5a1bdc',
    messagingSenderId: '409763267925',
    projectId: 'safdsaf-d85f6',
    databaseURL: 'https://safdsaf-d85f6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safdsaf-d85f6.appspot.com',
    iosClientId: '409763267925-59m555m3cmeqe4l538ocr5aaps7404oo.apps.googleusercontent.com',
    iosBundleId: 'com.example.test0415',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuiVpUbCZlL9ifgxE6SLin8-z7-hqGNpQ',
    appId: '1:409763267925:ios:fb1a9ac83529af6e5a1bdc',
    messagingSenderId: '409763267925',
    projectId: 'safdsaf-d85f6',
    databaseURL: 'https://safdsaf-d85f6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'safdsaf-d85f6.appspot.com',
    iosClientId: '409763267925-59m555m3cmeqe4l538ocr5aaps7404oo.apps.googleusercontent.com',
    iosBundleId: 'com.example.test0415',
  );
}
