// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp-UydTsa0_2IW-20Bjx8nYxnYww8jIM4',
    appId: '1:217766234276:web:afd8bd8ad6d18cc2723e31',
    messagingSenderId: '217766234276',
    projectId: 'taeil-test',
    authDomain: 'taeil-test.firebaseapp.com',
    databaseURL: 'https://taeil-test-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taeil-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6UP5VgDA0Hso1O9PRkCbzgP6L0YlViFg',
    appId: '1:217766234276:android:f39ad5d51f4c4a33723e31',
    messagingSenderId: '217766234276',
    projectId: 'taeil-test',
    databaseURL: 'https://taeil-test-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taeil-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm42taDRqI-8F8Fowh_H2KwKqX7wfRWkE',
    appId: '1:217766234276:ios:a014084964f9c9ab723e31',
    messagingSenderId: '217766234276',
    projectId: 'taeil-test',
    databaseURL: 'https://taeil-test-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taeil-test.appspot.com',
    iosClientId: '217766234276-fo2b4qpfivevroq1ajpfmpo3tot5sold.apps.googleusercontent.com',
    iosBundleId: 'com.example.test0415',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm42taDRqI-8F8Fowh_H2KwKqX7wfRWkE',
    appId: '1:217766234276:ios:a014084964f9c9ab723e31',
    messagingSenderId: '217766234276',
    projectId: 'taeil-test',
    databaseURL: 'https://taeil-test-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taeil-test.appspot.com',
    iosClientId: '217766234276-fo2b4qpfivevroq1ajpfmpo3tot5sold.apps.googleusercontent.com',
    iosBundleId: 'com.example.test0415',
  );
}
